### PR TITLE
#134 Change default directory of mocha from test to tests

### PR DESCRIPTION
**Pull request by Leos1113**

### CODE REVIEW

**Review by Pinjasaur — CHANGES_REQUESTED** [review]
Hey @Leos1113, thanks for the contribution. Much appreciated!

My only feedback is I see there's a `package-lock.json` that is in the commit—that shouldn't be there as we use [yarn](https://yarnpkg.com/) which is indicated by the `yarn.lock` file.

Please remove that file. Otherwise the PR looks great. 👍

**Comment by Leos1113** [comment]
Done :)

**Review by Pinjasaur — APPROVED** [review]
Thanks! :)

**Comment by Pinjasaur** [comment]
Closes #134.

**Pull request merged**
